spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/diplomainfo?serverTimezone=UTC
